### ISSUE TITLE
add a garbage collection torture image?

### ISSUE THREAD

**Issue by jackwasey** [r-hub/feedback#10]
Would a `R CMD check --use-gct` enabled image be feasible?

This would nicely complement valgrind and santitizer checks, and was mentioned again in the recent controversial Tomas Kalibera post, in combination with the sanitizer. It will run slow, and therefore may be too resource intensive, but would be a welcome addition. It would also face the ten-minute timeout issue.

Thanks for this amazing work.

**Comment by gaborcsardi** [comment]
I think you can specify `--use-gct` as a check option:
```r
rhub::check(..., check_args = "--use-gct")
```

but I would suggest to do this on your local computer, because it will be very slow, and you will hold up an R-hub builder for a long time, and also it will probably timeout.

**Comment by jackwasey** [comment]
Sounds good - I'll just do that locally, and I can understand why you wouldn't encourage it on rhub. It would probably time-out for no output anyway.

I wonder whether you might consider rate-limiting slower builds like this and valgrdin, or by user, or by package as a way for rhub to be able to run such checks, without swamping your resources? I've found so much value in being able to access multiple platforms when debugging compiled code R packages. Thanks again.
