### ISSUE TITLE
Declaring a dependency on R-forge

### ISSUE THREAD

**Issue by dmurdoch** [r-hub/feedback#2]
I'm trying to run the rgl package through the builder.  The current unreleased version of rgl depends on an unreleased version of rglwidget which lives on R-forge.

The svn address for rglwidget on R-forge is 

```
https://svn.r-forge.r-project.org/svnroot/rgl/pkg/rglwidget
```

but putting this into a Remotes entry (with "svn::" prefix) in the rgl DESCRIPTION file leads to this error:

```
#> Downloading svn repo https://svn.r-forge.r-project.org/svnroot/rgl/pkg/rglwidget
#> '/usr/bin/svn' co https://svn.r-forge.r-project.org/svnroot/rgl/pkg/rglwidget/trunk /tmp/Rtmp7fbT4U/file595cabba89
#> Error: There seems to be a problem retrieving this SVN-URL.
```

(There is no "trunk" subdir; R-forge has its own weird organization.)

There's a Github mirror of R-forge.  On that mirror, rglwidget lives here:

```
https://github.com/rforge/rgl/tree/master/pkg/rglwidget
```

However, neither of

```
Remotes:  rforge/rgl/tree/master/pkg/rglwidget
Remotes:  rforge/rglwidget
```

works.  Is there some way to specify the rglwidget dependency?

**Comment by dmurdoch** [comment]
Working syntax appears to be

```
Remotes:  rforge/rgl/pkg/rglwidget
```

However, this isn't enough to get rgl built and checked.  The check fails with this message:

```
* checking package dependencies ... ERROR
Package required and available but unsuitable version: ���rglwidget���
```

The one on github is a suitable version, but the one on CRAN isn't.   Looking further back in the log, 
I see the following when rglwidget was installed:

```
* installing *source* package ���rglwidget��� ...
** R
** demo
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ���rgl��� 0.95.1441 is being loaded, but >= 0.95.1456 is required
```

0.95.1441 is the rgl version on CRAN, 0.95.1492 version I'm trying to build and check.  So why is r-hub looking on CRAN, when it has the correct version already installed?  (rglwidget is just a Suggests dependency, so the rgl install has already happened.)

**Comment by dmurdoch** [comment]
The SVN url that I listed in the first comment requires write access; the public one is

```
svn://svn.r-forge.r-project.org/svnroot/rgl/pkg/rglwidget
```

However, the Remotes field doesn't keep the `https` part.  The problem appears to be that `devtools::install_svn` forces SVN urls to contain "trunk" or "branches".  I've added an issue on the `devtools` page.

**Comment by gaborcsardi** [comment]
@dmurdoch Duncan, I am sorry for not replying, I was travelling. 

Anyway, yes, the SVN issue might be a bug. We don't use `devtools`, but a package I wrote called `remotes`. `devtools` is too heavy and `remotes` has no dependencies. But much of the code in `remotes` is from `devtools`, do it is probably the same issue.

I'll try to take a look at it soon.

**Comment by gaborcsardi** [comment]
> So why is r-hub looking on CRAN, when it has the correct version already installed? 

I think this is another `remotes` bug: https://github.com/MangoTheCat/remotes/issues/32

**Comment by dmurdoch** [comment]
The `install_svn` problem is actually in `remote_download.svn_remote`; it's the same in `remotes` as in `devtools`.  The problem is the assumption that all svn repositories have the conventional structure.  I could send you a patch to do it in a way that makes more sense from an svn point of view, but it would not be compatible with the current implementation.  (I can't do this for a while, I'm on the road right now.)

**Comment by gaborcsardi** [comment]
With your `remotes` fixes, this should be fine I believe, with the SVN link in `Remotes`. 

But do not include the `rgl` package itself in `Remotes`, because the infinite loop is still not fixed.

**Comment by gaborcsardi** [comment]
I think this is fixed now. Please reopen if not.
