### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by dmurdoch** [r-hub/feedback#3]
I put "Remotes" declarations into rgl and rglwidget in an attempt to solve https://github.com/r-hub/feedback/issues/2.  This has apparently put R-hub into an infinite loop:  I'm seeing

```
#> Downloading GitHub repo rforge/rgl@master
#> Downloading GitHub repo rforge/rgl@master
#> Downloading GitHub repo rforge/rgl@master
...
```

(so far about 60 times).  Hopefully it will eventually time out.  The job is

https://builder.r-hub.io/status/rgl_0.95.1492.tar.gz-573a18a74d53e00cdf483d921300c462

(Edited to add:  It did die after 17 minutes and 184 attempts.)

**Comment by gaborcsardi** [comment]
Thanks for testing! Yes, this the issue here: https://github.com/MangoTheCat/remotes/issues/31
Once that is solved, all should be fine. I'll try to fix it soon.
