### ISSUE TITLE
rmarkdown vignette error

### ISSUE THREAD

**Issue by dmurdoch** [r-hub/feedback#4]
The `rgl` package has a couple of `rmarkdown` vignettes.  They are processed without errors on my machine, but on builder `R CMD check` fails with this error:

```
* checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
Warning in (if (grepl("\\.[Rr]md$", file)) knit2html else if (grepl("\\.[Rr]rst$",  :
  It seems you should call rmarkdown::render() instead of knitr::knit2html() because rgl.Rmd appears to be an R Markdown v2 document.
Quitting from lines 58-61 (rgl.Rmd) 
Error: processing vignette 'rgl.Rmd' failed with diagnostics:
Please install the webshot package (if not on CRAN, try devtools::install_github("wch/webshot"))
Execution halted
```

The quoted code in the warning is from `knitr`, not from `rgl`.  I think the yaml entries in the vignette are correct:

```

---
title: "rgl Overview"
author: "Duncan Murdoch"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  rmarkdown::html_vignette:
    toc: yes
    fig_width: 5
    fig_height: 5
vignette: >
  %\VignetteIndexEntry{rgl Overview} 
  %\VignetteEngine{knitr::rmarkdown}

---
```

so I can't figure out why I'm getting the warning.

**Comment by gaborcsardi** [comment]
Probably an error in r-hub, more precisely the remotes package. Will take a
look.

G.

**Comment by gaborcsardi** [comment]
Actually, maybe not r-hub's fault. I think you need to specify `rmarkdown` as the vignette builder, not `knitr`. This is probably sg relatively new in `knitr`. E.g. like this:
https://github.com/ropensci/rentrez/commit/8ee84ba29472f56f3f92bf65511e1a29121882d4

You'll also need the `webshot` package, so maybe put that into `Suggests`. This is also new in `knitr`, it is trying to take a screenshot or the html widget.

**Comment by dmurdoch** [comment]
I hope a change to `VignetteBuilder` is not necessary:  there are hundreds of packages on CRAN using `VignetteBuilder: knitr`.  I can't tell how many of them are using `rmarkdown::html_vignette`, but probably a lot are.

Needing `webshot` would be disappointing, because I think it doesn't work with WebGL, but maybe there's a way to get that to work.

**Comment by gaborcsardi** [comment]
I think you are right, and the error messages might be misleading, actually. 

Maybe this is because there is no X11 server on the builder, only a fake (xvfb) one? Similarly to Travis where this error happened frequently.

**Comment by gaborcsardi** [comment]
I just built `tidyr`, which has the same vignette config afaict (https://github.com/hadley/tidyr), and it all went fine: https://builder.r-hub.io/status/tidyr_0.5.1.9000.tar.gz-11959a43b51ff876b5f0f2e252bae13b

I'll try checking rgl in the docker container by hand tomorrow.

**Comment by gaborcsardi** [comment]
I think this is OK now with the current images: https://builder.r-hub.io/status/rgl_0.96.0.tar.gz-c74cc28d09804060927a3e53288054d0

I cannot fix the GLX error currently. The virtual X server (xvfb) does not support GLX.
