### ISSUE TITLE
complaints about non used imports 

### ISSUE THREAD

**Issue by petermeissner** [r-hub/feedback#6]
Using `rhub::check_for_cran()` on https://github.com/petermeissner/diffrprojects (and others too) I usually get complaints about unused imports. 

I suspect it is triggered by me often using something like `dplyr::select()` instead of explicitly importing via Roxygen `#' @import dplyr` or `#' @importFrom`. However I do not get those (in my opinion false) complaints using local checks (`devtools::check_cran()`) or e.g. Travis https://travis-ci.org/petermeissner/diffrprojects 

Any ideas?

**Comment by petermeissner** [comment]
OK, 
I double checked and did a local build and check on Ubuntu 14.04 / R 3.3.2 (complaints about the following packages within DESCRIPTION / Imports but without actually using them) and it turns out:
- some complaints were correct (‘graphics’ 'tidyr’, 'dtplyr')
- while the rest really really is used directly throughout the package (( ‘Rcpp’ ‘data.table’))

My take away so far is that Waht gets detected and with which accuracy is highly system and R-version dependent - but I am supprised about the actual variance.

**Comment by gaborcsardi** [comment]
This is what I get on Ubuntu and R-devel for your latest GH version:

```
N  checking dependencies in R code
   Namespaces in Imports field not imported from:
     ‘data.table’ ‘dtplyr’ ‘graphics’ ‘Rcpp’ ‘tidyr’
     All declared Imports should be used.
```
- `data.table` is not used, except in examples, so it should be in `Suggests`.
- Same for `dtplyr`. This is actually never used directly even in examples.
- You don't import anything from `graphics`.
- `Rcpp` is only used from C++. This is a false positive in the check. Note that the check is not mine, it is CRAN's, so I cannot fix it. Just import something (anything) from `Rcpp`.
- `tidyr` is never used on your package.

**Comment by petermeissner** [comment]
Thanks again.

**Comment by gaborcsardi** [comment]
No worries.
