### ISSUE TITLE
can the time-out limit be specified?

### ISSUE THREAD

**Issue by dankelley** [r-hub/feedback#8]
I develop on MacOS, and it's quite hard to set up valgrind for this platform, so `rhub::check_valgrind()` would seem to be very helpful to me. However, it times out at 22 minutes, on my project (the `oce` package). 

I wonder if there is a workaround for this, e.g. a way of asking for a N-minute limit on a delay over (N/10) days or something. I'm just pulling the factor 1/10 out of my hat, but I imagine most people would be like me -- guessing a test of under 60min and being most happy to get a result in 6 days.

Probably I'm missing something, but I don't see anything on https://builder.r-hub.io that seems to link to documentation.

**Comment by gaborcsardi** [comment]
I don't think there is a hard time limit, but there is a time limit for 10 minutes without output. Can you point me to a build?

**Comment by dankelley** [comment]
Hi. I had to resubmit it, since I had deleted the email.  Below is the link it provided for this build that I just did.  I know valgrind makes things really slow in general, and from my own local tests, I'd guess that the problem is in doing either the code in the help pages, or the testthat test suite.

https://builder.r-hub.io/status/oce_0.9-22.tar.gz-72dfd147431c4dd6a44d2a02d2aa87c0

**Comment by gaborcsardi** [comment]
It seems hard to make R CMD check produce output here, but we could
increase the 10 minute limit for these jobs.

**Comment by dankelley** [comment]
It might be smart to have some sort of submission configuration item for requesting longer times. That way, extra time would only be allotted in cases where the submitter is aware of the issue.  My guess is that this might come up fairly often with valgrind tests, because valgrind is so very slow.  In case it's of interest, I submitted this via `rhub::check_with_valgrind`, not by uploading a file manually.

**Comment by gaborcsardi** [comment]
You can maybe run a subset of the tests, so it does not timeout?

**Comment by gaborcsardi** [comment]
CLosing this now, please reopen if you cannot work around it.

**Comment by jackwasey** [comment]
Try this: it generates a test_check file in `tests` for each `tests/testthat` test file, so each file will output, instead of the whole lot at once.

This doesn't seem in scope for r-hub to handle itself, does it? I have also run into the timeout issue with `check_with_valgrind`.

```
# convert testthat (or I guess test-all.R) to multiple calls to test_check in the tests directory, so that CI builders don't time out, notably r-hub valgrind, and probably gcc torture if that is available.

# source from package root after setting `dry_run` to `FALSE`

# run from package root. adjust the following as required:
base_name <- "test-all" # testthat is default from usethis_testthat
dry_run = TRUE
restore = FALSE

test_all <- file.path("tests", paste0(base_name, ".R"))
test_all_disabled <- file.path(paste0(base_name, "-disabled.R"))
prefix <- "testthat-split-"

testthat_split <- function() {
  test_files <- list.files(
    file.path("tests", "testthat"),
    pattern = "^test-"
  )

  for (f in test_files) {
    test_name <- sub(".R", "", x = sub("test-", "", x = f))
    new_test <- file.path("tests", paste0(prefix, test_name, ".R"))
    new_test_lines <- readLines(test_all)
    test_check_line_num <- grep("^ *[^#]*(testthat::)?test_check.*",
                                new_test_lines)
    test_check_line <- new_test_lines[test_check_line_num]
    test_check_line <- sub(pattern = "\\)",
                           replacement = paste0(", filter = \"^", test_name, "$\")"),
                           test_check_line)
    new_test_lines[test_check_line_num] <- test_check_line
    if (!dry_run) writeLines(new_test_lines, new_test)
  }
  if (!dry_run) file.rename(test_all, test_all_disabled)
  invisible()
}

testthat_restore <- function() {
  file.rename(test_all_disabled, test_all)
  ok <- all(file.remove(list.files("tests", pattern = paste0(prefix),
                         full.names = TRUE)))
  stopifnot(ok)
}

if (restore) {
  testthat_restore()
} else {
  testthat_split()
}
```
