### ISSUE TITLE
Pin this repo?

### ISSUE THREAD

**Issue by maelle** [r-hub/feedback#9]
Would it make sense (before the about page is ready) to:

* pin this repo

* make its description say something like "Place for you to give feedback about R-hub" (the current description is clear but could be clearer I think?)

* add a few details about the kind of feedback expected here in the README? E.g. general questions and feature suggestions, bug reports, for when the user doesn't know in which specific repo to open the issue in?

**Comment by gaborcsardi** [comment]
It is probably my failure, but people don't report  errors here, they tend to report them in `r-hub/rhub`, so I would just remove  this repo  and point people there.

**Comment by maelle** [comment]
https://github.com/r-hub/devops-issues/issues/27
